import { 
  Box, 
  Ruler, 
  Layers, 
  MousePointer2, 
  Instagram, 
  MessageCircle,
  Play,
  FileText,
  Award,
  Library,
  HelpCircle,
  Settings,
  Layout,
  Video,
  FileCode,
  Globe,
  Share2,
  Download,
  ExternalLink,
  Users,
  Building2
} from 'lucide-react';

export interface Lesson {
  id: string;
  title: string;
  videoId: string;
  duration: string;
}

export interface Module {
  id: string;
  title: string;
  lessons: Lesson[];
}

export const COURSE_DATA: Module[] = [
  {
    id: 'm1',
    title: 'Módulo 1: Introdução ao Revit',
    lessons: [
      { id: 'l1', title: 'Instalação e Interface', videoId: 'dQw4w9WgXcQ', duration: '10:00' },
      { id: 'l2', title: 'Configurações Iniciais', videoId: 'dQw4w9WgXcQ', duration: '12:00' },
    ]
  },
  {
    id: 'm2',
    title: 'Módulo 2: Modelagem Básica',
    lessons: [
      { id: 'l3', title: 'Paredes e Pisos', videoId: 'dQw4w9WgXcQ', duration: '15:00' },
      { id: 'l4', title: 'Portas e Janelas', videoId: 'dQw4w9WgXcQ', duration: '18:00' },
    ]
  }
];

export const COMMANDS = {
  'NaaviBee1': [
    { id: 'aulas', name: 'Aulas', icon: Video, description: 'Mapa de aulas do curso' },
    { id: 'cursos', name: 'Cursos', icon: Award, description: 'Nossos cursos e certificados' },
    { id: 'familias', name: 'Familias', icon: Library, description: 'Biblioteca de famílias Revit' },
    { id: 'fachada', name: 'Espessura Fachada', icon: Building2, description: 'Espessura de linha de fachadas' },
    { id: 'vip', name: 'Grupo VIP', icon: Users, description: 'Acesse o grupo VIP' },
    { id: 'instagram', name: 'Instagram', icon: Instagram, description: 'Siga Alan no Instagram' },
    { id: 'whatsapp', name: 'Whatsapp', icon: MessageCircle, description: 'Fale com o suporte' }
  ],
  'Architecture': [
    { id: 'modify', name: 'Modify', icon: 'Modify', description: 'Modify element' },
    { id: 'wall', name: 'Wall', icon: 'Wall', description: 'Create a wall' },
    { id: 'door', name: 'Door', icon: 'Door', description: 'Place a door' },
    { id: 'window', name: 'Window', icon: 'Window', description: 'Place a window' },
    { id: 'component', name: 'Component', icon: 'Component', description: 'Place a component' },
    { id: 'column', name: 'Column', icon: 'Column', description: 'Place a column' },
    { id: 'roof', name: 'Roof', icon: 'Roof', description: 'Create a roof' },
    { id: 'ceiling', name: 'Ceiling', icon: 'Ceiling', description: 'Create a ceiling' },
    { id: 'floor', name: 'Floor', icon: 'Floor', description: 'Create a floor' },
    { id: 'curtainsystem', name: 'Curtain System', icon: 'CurtainSystem', description: 'Create a curtain system' },
    { id: 'curtaingrid', name: 'Curtain Grid', icon: 'CurtainGrid', description: 'Create a curtain grid' },
    { id: 'mullion', name: 'Mullion', icon: 'Mullion', description: 'Create a mullion' },
    { id: 'railing', name: 'Railing', icon: 'Railing', description: 'Create a railing' },
    { id: 'ramp', name: 'Ramp', icon: 'Ramp', description: 'Create a ramp' },
    { id: 'stair', name: 'Stair', icon: 'Stair', description: 'Create a stair' },
    { id: 'modeltext', name: 'Model Text', icon: 'ModelText', description: 'Create model text' },
    { id: 'modelline', name: 'Model Line', icon: 'ModelLine', description: 'Create a model line' },
    { id: 'modelgroup', name: 'Model Group', icon: 'ModelGroup', description: 'Create a model group' },
    { id: 'room', name: 'Room', icon: 'Room', description: 'Place a room' },
    { id: 'roomseparator', name: 'Room Separator', icon: 'RoomSeparator', description: 'Create a room separator' },
    { id: 'tagroom', name: 'Tag Room', icon: 'TagRoom', description: 'Tag a room' },
    { id: 'area', name: 'Area', icon: 'Area', description: 'Create an area' },
    { id: 'areaboundary', name: 'Area Boundary', icon: 'AreaBoundary', description: 'Create an area boundary' },
    { id: 'tagarea', name: 'Tag Area', icon: 'TagArea', description: 'Tag an area' },
    { id: 'byface', name: 'By Face', icon: 'ByFace', description: 'Create by face' },
    { id: 'shaft', name: 'Shaft', icon: 'Shaft', description: 'Create a shaft' },
    { id: 'wall', name: 'Wall', icon: 'WallOpening', description: 'Create a wall opening' },
    { id: 'vertical', name: 'Vertical', icon: 'Vertical', description: 'Create a vertical opening' },
    { id: 'dormer', name: 'Dormer', icon: 'Dormer', description: 'Create a dormer opening' },
    { id: 'level', name: 'Level', icon: 'Level', description: 'Create a level' },
    { id: 'grid', name: 'Grid', icon: 'Grid', description: 'Create a grid' },
    { id: 'set', name: 'Set', icon: 'Set', description: 'Set work plane' },
    { id: 'show', name: 'Show', icon: 'Show', description: 'Show work plane' },
    { id: 'refplane', name: 'Ref Plane', icon: 'RefPlane', description: 'Create a reference plane' },
    { id: 'viewer', name: 'Viewer', icon: 'Viewer', description: 'Open viewer' }
  ],
  'Annotate': [
    { id: 'modify', name: 'Modify', icon: 'Modify', description: 'Modify element' },
    { id: 'dimension', name: 'Aligned', icon: 'Aligned', description: 'Create an aligned dimension' },
    { id: 'linear', name: 'Linear', icon: 'Linear', description: 'Create a linear dimension' },
    { id: 'angular', name: 'Angular', icon: 'Angular', description: 'Create an angular dimension' },
    { id: 'radial', name: 'Radial', icon: 'Radial', description: 'Create a radial dimension' },
    { id: 'diameter', name: 'Diameter', icon: 'Diameter', description: 'Create a diameter dimension' },
    { id: 'arclength', name: 'Arc Length', icon: 'ArcLength', description: 'Create an arc length dimension' },
    { id: 'spotelevation', name: 'Spot Elevation', icon: 'SpotElevation', description: 'Create a spot elevation' },
    { id: 'spotcoordinate', name: 'Spot Coordinate', icon: 'SpotCoordinate', description: 'Create a spot coordinate' },
    { id: 'spotslope', name: 'Spot Slope', icon: 'SpotSlope', description: 'Create a spot slope' },
    { id: 'detailline', name: 'Detail Line', icon: 'DetailLine', description: 'Create a detail line' },
    { id: 'region', name: 'Region', icon: 'Region', description: 'Create a region' },
    { id: 'component', name: 'Component', icon: 'DetailComponent', description: 'Place a detail component' },
    { id: 'revisioncloud', name: 'Revision Cloud', icon: 'RevisionCloud', description: 'Create a revision cloud' },
    { id: 'detailgroup', name: 'Detail Group', icon: 'DetailGroup', description: 'Create a detail group' },
    { id: 'insulation', name: 'Insulation', icon: 'Insulation', description: 'Create insulation' },
    { id: 'text', name: 'Text', icon: 'Text', description: 'Add text annotation' },
    { id: 'checkspelling', name: 'Check Spelling', icon: 'CheckSpelling', description: 'Check spelling' },
    { id: 'findreplace', name: 'Find/Replace', icon: 'FindReplace', description: 'Find and replace text' },
    { id: 'tagbycategory', name: 'Tag by Category', icon: 'TagByCategory', description: 'Tag by category' },
    { id: 'tagall', name: 'Tag All', icon: 'TagAll', description: 'Tag all' },
    { id: 'beamannotations', name: 'Beam Annotations', icon: 'BeamAnnotations', description: 'Beam annotations' },
    { id: 'multicategory', name: 'Multi-Category', icon: 'MultiCategory', description: 'Multi-category tag' },
    { id: 'materialtag', name: 'Material Tag', icon: 'MaterialTag', description: 'Material tag' },
    { id: 'areatag', name: 'Area Tag', icon: 'AreaTag', description: 'Area tag' },
    { id: 'roomtag', name: 'Room Tag', icon: 'RoomTag', description: 'Room tag' },
    { id: 'spacetag', name: 'Space Tag', icon: 'SpaceTag', description: 'Space tag' },
    { id: 'viewreference', name: 'View Reference', icon: 'ViewReference', description: 'View reference' },
    { id: 'treadnumber', name: 'Tread Number', icon: 'TreadNumber', description: 'Tread number' },
    { id: 'multirebar', name: 'Multi-Rebar', icon: 'MultiRebar', description: 'Multi-rebar tag' },
    { id: 'keynote', name: 'Keynote', icon: 'Keynote', description: 'Keynote' },
    { id: 'ductlegend', name: 'Duct Legend', icon: 'DuctLegend', description: 'Duct legend' },
    { id: 'pipelegend', name: 'Pipe Legend', icon: 'PipeLegend', description: 'Pipe legend' },
    { id: 'colorfilllegend', name: 'Color Fill Legend', icon: 'ColorFillLegend', description: 'Color fill legend' },
    { id: 'symbol', name: 'Symbol', icon: 'Symbol', description: 'Place a symbol' },
    { id: 'spandirection', name: 'Span Direction', icon: 'SpanDirection', description: 'Span direction' },
    { id: 'beam', name: 'Beam', icon: 'BeamSymbol', description: 'Beam symbol' },
    { id: 'stairpath', name: 'Stair Path', icon: 'StairPath', description: 'Stair path' },
    { id: 'area', name: 'Area', icon: 'AreaSymbol', description: 'Area symbol' },
    { id: 'path', name: 'Path', icon: 'PathSymbol', description: 'Path symbol' },
    { id: 'rebar', name: 'Rebar', icon: 'RebarSymbol', description: 'Rebar symbol' },
    { id: 'fabric', name: 'Fabric', icon: 'FabricSymbol', description: 'Fabric symbol' }
  ],
  'Structure': [
    { id: 'beam', name: 'Beam', icon: 'Beam', description: 'Create a beam' },
    { id: 'truss', name: 'Truss', icon: 'Truss', description: 'Create a truss' },
    { id: 'brace', name: 'Brace', icon: 'Brace', description: 'Create a brace' },
    { id: 'beamsystem', name: 'Beam System', icon: 'BeamSystem', description: 'Create a beam system' },
    { id: 'connection', name: 'Connection', icon: 'Connection', description: 'Create a connection' },
    { id: 'connectionautomation', name: 'Connection Automation', icon: 'ConnectionAutomation', description: 'Create a connection automation' },
    { id: 'isolated', name: 'Isolated', icon: 'Isolated', description: 'Create an isolated foundation' },
    { id: 'wallfoundation', name: 'Wall Foundation', icon: 'WallFoundation', description: 'Create a wall foundation' },
    { id: 'slab', name: 'Slab', icon: 'Slab', description: 'Create a structural slab' }
  ],
  'Concrete': [
    { id: 'modify', name: 'Modify', icon: 'Modify', description: 'Modify element' },
    { id: 'rebar', name: 'Rebar', icon: 'Rebar', description: 'Create rebar' },
    { id: 'path', name: 'Path', icon: 'Path', description: 'Create path reinforcement' },
    { id: 'morphed', name: 'Morphed', icon: 'Morphed', description: 'Create morphed reinforcement' },
    { id: 'area', name: 'Area', icon: 'AreaReinforcement', description: 'Create area reinforcement' },
    { id: 'fabricarea', name: 'Fabric Area', icon: 'FabricArea', description: 'Create fabric area' },
    { id: 'fabricsheet', name: 'Fabric Sheet', icon: 'FabricSheet', description: 'Create fabric sheet' },
    { id: 'cover', name: 'Cover', icon: 'Cover', description: 'Set rebar cover' },
    { id: 'coversettings', name: 'Cover Settings', icon: 'CoverSettings', description: 'Rebar cover settings' },
    { id: 'reinforcementsettings', name: 'Reinforcement Settings', icon: 'ReinforcementSettings', description: 'Reinforcement settings' },
    { id: 'split', name: 'Split', icon: 'Split', description: 'Split element' },
    { id: 'mountingparts', name: 'Mounting Parts', icon: 'MountingParts', description: 'Add mounting parts' },
    { id: 'reinforcement', name: 'Reinforcement', icon: 'ReinforcementPrecast', description: 'Create precast reinforcement' },
    { id: 'customfabricsheet', name: 'Custom Fabric Sheet', icon: 'CustomFabricSheet', description: 'Create custom fabric sheet' },
    { id: 'shopdrawings', name: 'Shop Drawings', icon: 'ShopDrawings', description: 'Create shop drawings' },
    { id: 'camexport', name: 'CAM Export', icon: 'CAMExport', description: 'Export CAM data' },
    { id: 'configuration', name: 'Configuration', icon: 'Configuration', description: 'Configuration' },
    { id: 'cfsconfig', name: 'CFS Config', icon: 'CFSConfig', description: 'CFS configuration' },
    { id: 'set', name: 'Set', icon: 'Set', description: 'Set work plane' },
    { id: 'show', name: 'Show', icon: 'Show', description: 'Show work plane' },
    { id: 'refplane', name: 'Ref Plane', icon: 'RefPlane', description: 'Create a reference plane' },
    { id: 'viewer', name: 'Viewer', icon: 'Viewer', description: 'Open viewer' }
  ],
  'Collaborate': [
    { id: 'modify', name: 'Modify', icon: 'Modify', description: 'Modify element' },
    { id: 'editingrequests', name: 'Editing Requests', icon: 'EditingRequests', description: 'View editing requests' },
    { id: 'collaborate', name: 'Collaborate', icon: 'Collaborate', description: 'Collaborate' },
    { id: 'worksets', name: 'Worksets', icon: 'Worksets', description: 'Manage worksets' },
    { id: 'synchronize', name: 'Synchronize with Central', icon: 'Synchronize', description: 'Synchronize with central model' },
    { id: 'reloadlatest', name: 'Reload Latest', icon: 'ReloadLatest', description: 'Reload latest' },
    { id: 'relinquishallmine', name: 'Relinquish All Mine', icon: 'RelinquishAllMine', description: 'Relinquish all mine' },
    { id: 'worksharingmonitor', name: 'Worksharing Monitor', icon: 'WorksharingMonitor', description: 'Worksharing monitor' },
    { id: 'showhistory', name: 'Show History', icon: 'ShowHistory', description: 'Show history' },
    { id: 'restorebackup', name: 'Restore Backup', icon: 'RestoreBackup', description: 'Restore backup' },
    { id: 'publishsettings', name: 'Publish Settings', icon: 'PublishSettings', description: 'Publish settings' },
    { id: 'managescenarios', name: 'Manage Scenarios', icon: 'ManageScenarios', description: 'Manage scenarios' },
    { id: 'copymonitor', name: 'Copy/Monitor', icon: 'CopyMonitor', description: 'Copy/monitor' },
    { id: 'coordinationreview', name: 'Coordination Review', icon: 'CoordinationReview', description: 'Coordination review' },
    { id: 'coordinationsettings', name: 'Coordination Settings', icon: 'CoordinationSettings', description: 'Coordination settings' },
    { id: 'reconcilehosting', name: 'Reconcile Hosting', icon: 'ReconcileHosting', description: 'Reconcile hosting' },
    { id: 'interferencecheck', name: 'Interference Check', icon: 'InterferenceCheck', description: 'Interference check' },
    { id: 'coordinationmodelchanges', name: 'Coordination Model Changes', icon: 'CoordinationModelChanges', description: 'Coordination model changes' },
    { id: 'issues', name: 'Issues', icon: 'Issues', description: 'Manage issues' },
    { id: 'sharedviews', name: 'Shared Views', icon: 'SharedViews', description: 'Shared views' }
  ],
  'Analyze': [
    { id: 'heatingcoolingloads', name: 'Heating and Cooling Loads', icon: 'HeatingCoolingLoads', description: 'Heating and cooling loads' },
    { id: 'panelschedules', name: 'Panel Schedules', icon: 'PanelSchedules', description: 'Panel schedules' },
    { id: 'schedulequantities', name: 'Schedule/ Quantities', icon: 'ScheduleQuantities', description: 'Schedule/ quantities' },
    { id: 'ductpressurerelief', name: 'Duct Pressure Loss Report', icon: 'DuctPressureLossReport', description: 'Duct pressure loss report' },
    { id: 'pipepressurerelief', name: 'Pipe Pressure Loss Report', icon: 'PipePressureLossReport', description: 'Pipe pressure loss report' },
    { id: 'checkductsystems', name: 'Check Duct Systems', icon: 'CheckDuctSystems', description: 'Check duct systems' },
    { id: 'checkpipesystems', name: 'Check Pipe Systems', icon: 'CheckPipeSystems', description: 'Check pipe systems' },
    { id: 'checkcircuits', name: 'Check Circuits', icon: 'CheckCircuits', description: 'Check circuits' },
    { id: 'showdisconnects', name: 'Show Disconnects', icon: 'ShowDisconnects', description: 'Show disconnects' },
    { id: 'ductlegend', name: 'Duct Legend', icon: 'DuctLegend', description: 'Duct legend' },
    { id: 'pipelegend', name: 'Pipe Legend', icon: 'PipeLegend', description: 'Pipe legend' },
    { id: 'colorfilllegend', name: 'Color Fill Legend', icon: 'ColorFillLegend', description: 'Color fill legend' },
    { id: 'analyseshistory', name: 'Analyses & History', icon: 'AnalysesHistory', description: 'Analyses & history' },
    { id: 'windsimulation', name: 'Wind Simulation', icon: 'WindSimulation', description: 'Wind simulation' },
    { id: 'windestimate', name: 'Wind Estimate', icon: 'WindEstimate', description: 'Wind estimate' },
    { id: 'location', name: 'Location', icon: 'Location', description: 'Location' },
    { id: 'createenergymodel', name: 'Create Energy Model', icon: 'CreateEnergyModel', description: 'Create energy model' },
    { id: 'energymodelsettings', name: 'Energy Model Settings', icon: 'EnergyModelSettings', description: 'Energy model settings' },
    { id: 'systemsanalysis', name: 'Systems Analysis', icon: 'SystemsAnalysis', description: 'Systems analysis' },
    { id: 'areabasedloadboundary', name: 'Area Based Load Boundary', icon: 'AreaBasedLoadBoundary', description: 'Area based load boundary' },
    { id: 'areabasedload', name: 'Area Based Load', icon: 'AreaBasedLoad', description: 'Area based load' },
    { id: 'equipmentload', name: 'Equipment Load', icon: 'EquipmentLoad', description: 'Equipment load' },
    { id: 'pathoftravel', name: 'Path of Travel', icon: 'PathofTravel', description: 'Path of travel' },
    { id: 'revealobstacles', name: 'Reveal Obstacles', icon: 'RevealObstacles', description: 'Reveal obstacles' },
    { id: 'multiplepaths', name: 'Multiple Paths', icon: 'MultiplePaths', description: 'Multiple paths' },
    { id: 'onewayindicator', name: 'One Way Indicator', icon: 'OneWayIndicator', description: 'One way indicator' },
    { id: 'peoplecontent', name: 'People Content', icon: 'PeopleContent', description: 'People content' },
    { id: 'spatialgrid', name: 'Spatial Grid', icon: 'SpatialGrid', description: 'Spatial grid' },
    { id: 'routeanalysis', name: 'Route Analysis', icon: 'RouteAnalysis', description: 'Route analysis' }
  ],
  'Insert': [
    { id: 'modify', name: 'Modify', icon: 'Modify', description: 'Modify element' },
    { id: 'managelinks', name: 'Manage Links', icon: 'ManageLinks', description: 'Manage links' },
    { id: 'linkrevit', name: 'Link Revit', icon: 'LinkRevit', description: 'Link Revit model' },
    { id: 'linkifc', name: 'Link IFC', icon: 'LinkIFC', description: 'Link IFC file' },
    { id: 'linkcad', name: 'Link CAD', icon: 'LinkCAD', description: 'Link CAD file' },
    { id: 'linktopography', name: 'Link Topography', icon: 'LinkTopography', description: 'Link topography' },
    { id: 'dwfmarkup', name: 'DWF Markup', icon: 'DWFMarkup', description: 'Link DWF markup' },
    { id: 'decal', name: 'Decal', icon: 'Decal', description: 'Place decal' },
    { id: 'pointcloud', name: 'Point Cloud', icon: 'PointCloud', description: 'Link point cloud' },
    { id: 'coordinationmodel', name: 'Coordination Model', icon: 'CoordinationModel', description: 'Link coordination model' },
    { id: 'linkpdf', name: 'Link PDF', icon: 'LinkPDF', description: 'Link PDF' },
    { id: 'linkimage', name: 'Link Image', icon: 'LinkImage', description: 'Link image' },
    { id: 'extendedproperties', name: 'Extended Properties', icon: 'ExtendedProperties', description: 'Manage extended properties' },
    { id: 'importcad', name: 'Import CAD', icon: 'ImportCAD', description: 'Import CAD file' },
    { id: 'importgbxml', name: 'Import gbXML', icon: 'ImportgbXML', description: 'Import gbXML file' },
    { id: 'importpdf', name: 'Import PDF', icon: 'ImportPDF', description: 'Import PDF' },
    { id: 'importimage', name: 'Import Image', icon: 'ImportImage', description: 'Import image' },
    { id: 'loadfamily', name: 'Load Family', icon: 'LoadFamily', description: 'Load a family' },
    { id: 'loadautodeskfamily', name: 'Load Autodesk Family', icon: 'LoadAutodeskFamily', description: 'Load Autodesk family' },
    { id: 'loadasgroup', name: 'Load as Group', icon: 'LoadasGroup', description: 'Load family as group' },
    { id: 'insertfromfile', name: 'Insert from File', icon: 'InsertfromFile', description: 'Insert from file' }
  ],
  'Massing & Site': [
    { id: 'showmass', name: 'Show Mass by View Settings', icon: 'ShowMass', description: 'Show mass by view settings' },
    { id: 'inplacemass', name: 'In-Place Mass', icon: 'InPlaceMass', description: 'Create in-place mass' },
    { id: 'placemass', name: 'Place Mass', icon: 'PlaceMass', description: 'Place mass' },
    { id: 'curtainsystem', name: 'Curtain System', icon: 'CurtainSystem', description: 'Create curtain system' },
    { id: 'roof', name: 'Roof', icon: 'Roof', description: 'Create roof' },
    { id: 'wall', name: 'Wall', icon: 'Wall', description: 'Create wall' },
    { id: 'floor', name: 'Floor', icon: 'Floor', description: 'Create floor' },
    { id: 'toposolid', name: 'Toposolid', icon: 'Toposolid', description: 'Create toposolid' },
    { id: 'contextualdata', name: 'Contextual Data', icon: 'ContextualData', description: 'Contextual data' },
    { id: 'toposolid2', name: 'Toposolid', icon: 'Toposolid', description: 'Create toposolid' },
    { id: 'sitecomponent', name: 'Site Component', icon: 'SiteComponent', description: 'Place site component' },
    { id: 'parkingcomponent', name: 'Parking Component', icon: 'ParkingComponent', description: 'Place parking component' },
    { id: 'propertyline', name: 'Property Line', icon: 'PropertyLine', description: 'Create property line' },
    { id: 'labelcontours', name: 'Label Contours', icon: 'LabelContours', description: 'Label contours' },
    { id: 'gradedregion', name: 'Graded Region', icon: 'GradedRegion', description: 'Create graded region' }
  ],
  'View': [
    { id: '3dview', name: '3D View', icon: 'Default3DView', description: 'Create a 3D view' },
    { id: 'section', name: 'Section', icon: 'Section', description: 'Create a section view' },
    { id: 'callout', name: 'Callout', icon: 'Callout', description: 'Create a callout view' },
    { id: 'planviews', name: 'Plan Views', icon: 'PlanViews', description: 'Create plan views' },
    { id: 'elevation', name: 'Elevation', icon: 'Elevation', description: 'Create an elevation view' },
    { id: 'draftingview', name: 'Drafting View', icon: 'DraftingView', description: 'Create a drafting view' },
    { id: 'legend', name: 'Legend', icon: 'Legend', description: 'Create a legend' },
    { id: 'schedule', name: 'Schedule/Quantities', icon: 'ScheduleQuantities', description: 'Create a schedule' },
    { id: 'sheet', name: 'Sheet', icon: 'Sheet', description: 'Create a sheet' },
    { id: 'visibilitygraphics', name: 'Visibility/Graphics', icon: 'VisibilityGraphics', description: 'Visibility/Graphics overrides' },
    { id: 'thinline', name: 'Thin Lines', icon: 'ThinLines', description: 'Toggle thin lines' },
    { id: 'showhiddenlines', name: 'Show Hidden Lines', icon: 'ShowHiddenLines', description: 'Show hidden lines' }
  ],
  'Manage': [
    { id: 'materials', name: 'Materials', icon: 'Materials', description: 'Manage materials' },
    { id: 'objectstyles', name: 'Object Styles', icon: 'ObjectStyles', description: 'Manage object styles' },
    { id: 'snaps', name: 'Snaps', icon: 'Snaps', description: 'Manage snaps' },
    { id: 'projectinformation', name: 'Project Information', icon: 'ProjectInformation', description: 'Manage project information' },
    { id: 'parametersservice', name: 'Parameters Service', icon: 'ParametersService', description: 'Manage parameters service' },
    { id: 'projectparameters', name: 'Project Parameters', icon: 'ProjectParameters', description: 'Manage project parameters' },
    { id: 'sharedparameters', name: 'Shared Parameters', icon: 'SharedParameters', description: 'Manage shared parameters' },
    { id: 'globalparameters', name: 'Global Parameters', icon: 'GlobalParameters', description: 'Manage global parameters' },
    { id: 'transferprojectstandards', name: 'Transfer Project Standards', icon: 'TransferProjectStandards', description: 'Transfer project standards' },
    { id: 'purgeunused', name: 'Purge Unused', icon: 'PurgeUnused', description: 'Purge unused' },
    { id: 'projectunits', name: 'Project Units', icon: 'ProjectUnits', description: 'Manage project units' },
    { id: 'numbering', name: 'Numbering', icon: 'Numbering', description: 'Manage numbering' },
    { id: 'structuralsettings', name: 'Structural Settings', icon: 'StructuralSettings', description: 'Manage structural settings' },
    { id: 'mepsettings', name: 'MEP Settings', icon: 'MEPSettings', description: 'Manage MEP settings' },
    { id: 'panelscheduletemplates', name: 'Panel Schedule Templates', icon: 'PanelScheduleTemplates', description: 'Manage panel schedule templates' },
    { id: 'additionalsettings', name: 'Additional Settings', icon: 'AdditionalSettings', description: 'Manage additional settings' },
    { id: 'location', name: 'Location', icon: 'Location', description: 'Manage location' },
    { id: 'coordinates', name: 'Coordinates', icon: 'Coordinates', description: 'Manage coordinates' },
    { id: 'position', name: 'Position', icon: 'Position', description: 'Manage position' },
    { id: 'designoptions', name: 'Design Options', icon: 'DesignOptions', description: 'Manage design options' },
    { id: 'createstudy', name: 'Create Study', icon: 'CreateStudy', description: 'Create study' },
    { id: 'exploreoutcomes', name: 'Explore Outcomes', icon: 'ExploreOutcomes', description: 'Explore outcomes' },
    { id: 'managelinks', name: 'Manage Links', icon: 'ManageLinks', description: 'Manage links' },
    { id: 'decaltypes', name: 'Decal Types', icon: 'DecalTypes', description: 'Manage decal types' },
    { id: 'startingview', name: 'Starting View', icon: 'StartingView', description: 'Set starting view' },
    { id: 'phases', name: 'Phases', icon: 'Phases', description: 'Manage phases' },
    { id: 'save', name: 'Save', icon: 'Save', description: 'Save' },
    { id: 'load', name: 'Load', icon: 'Load', description: 'Load' },
    { id: 'edit', name: 'Edit', icon: 'Edit', description: 'Edit' },
    { id: 'idsofselection', name: 'IDs of Selection', icon: 'IDsOfSelection', description: 'IDs of selection' },
    { id: 'selectbyid', name: 'Select by ID', icon: 'SelectByID', description: 'Select by ID' },
    { id: 'warnings', name: 'Warnings', icon: 'Warnings', description: 'Manage warnings' },
    { id: 'addinsmanager', name: 'Add-Ins Manager', icon: 'AddInsManager', description: 'Manage add-ins' },
    { id: 'macromanager', name: 'Macro Manager', icon: 'MacroManager', description: 'Manage macros' },
    { id: 'macrosecurity', name: 'Macro Security', icon: 'MacroSecurity', description: 'Manage macro security' },
    { id: 'dynamo', name: 'Dynamo', icon: 'Dynamo', description: 'Open Dynamo' },
    { id: 'dynamoplayer', name: 'Dynamo Player', icon: 'DynamoPlayer', description: 'Open Dynamo Player' }
  ],
  'Add-Ins': [
    { id: 'modify', name: 'Modify', icon: 'Modify', description: 'Select element' },
    { id: 'transmitmodels', name: 'Transmit model(s)', icon: 'TransmitModels', description: 'Transmit model(s)' },
    { id: 'help', name: 'Help', icon: 'Help', description: 'Help' },
    { id: 'about', name: 'About', icon: 'About', description: 'About' },
    { id: 'convertrfatoformit', name: 'Convert RFA to FormIt', icon: 'ConvertRFAtoFormIt', description: 'Convert RFA to FormIt' }
  ],
  'Modify': [
    { id: 'modify', name: 'Modify', icon: 'Modify', description: 'Modify element' },
    { id: 'align', name: 'Align', icon: 'Align', description: 'Align elements' },
    { id: 'offset', name: 'Offset', icon: 'Offset', description: 'Offset elements' },
    { id: 'mirror', name: 'Mirror', icon: 'Mirror', description: 'Mirror elements' },
    { id: 'move', name: 'Move', icon: 'Move', description: 'Move elements' },
    { id: 'copy', name: 'Copy', icon: 'Copy', description: 'Copy elements' },
    { id: 'rotate', name: 'Rotate', icon: 'Rotate', description: 'Rotate elements' },
    { id: 'trim', name: 'Trim', icon: 'Trim', description: 'Trim elements' },
    { id: 'split', name: 'Split', icon: 'Split', description: 'Split elements' },
    { id: 'array', name: 'Array', icon: 'Array', description: 'Array elements' },
    { id: 'scale', name: 'Scale', icon: 'Scale', description: 'Scale elements' },
    { id: 'pin', name: 'Pin', icon: 'Pin', description: 'Pin elements' },
    { id: 'delete', name: 'Delete', icon: 'Delete', description: 'Delete elements' }
  ],
  'System': [
    { id: 'duct', name: 'Duct', icon: 'Duct', description: 'Create a duct' },
    { id: 'ductplaceholder', name: 'Duct Placeholder', icon: 'DuctPlaceholder', description: 'Create a duct placeholder' },
    { id: 'ductfitting', name: 'Duct Fitting', icon: 'DuctFitting', description: 'Create a duct fitting' },
    { id: 'ductaccessory', name: 'Duct Accessory', icon: 'DuctAccessory', description: 'Create a duct accessory' },
    { id: 'converttoflexduct', name: 'Convert to Flex Duct', icon: 'ConvertToFlexDuct', description: 'Convert to flex duct' },
    { id: 'flexduct', name: 'Flex Duct', icon: 'FlexDuct', description: 'Create a flex duct' },
    { id: 'airterminal', name: 'Air Terminal', icon: 'AirTerminal', description: 'Place an air terminal' },
    { id: 'fabricationpart', name: 'Fabrication Part', icon: 'FabricationPart', description: 'Place a fabrication part' },
    { id: 'multipointrouting', name: 'Multi-Point Routing', icon: 'MultiPointRouting', description: 'Multi-point routing' },
    { id: 'ductworkstiffener', name: 'Ductwork Stiffener', icon: 'DuctworkStiffener', description: 'Create a ductwork stiffener' },
    { id: 'pidmodeler', name: 'P&ID Modeler', icon: 'PIDModeler', description: 'Open P&ID Modeler' },
    { id: 'mechanicalequipment', name: 'Mechanical Equipment', icon: 'MechanicalEquipment', description: 'Place mechanical equipment' },
    { id: 'mechanicalcontroldevice', name: 'Mechanical Control Device', icon: 'MechanicalControlDevice', description: 'Place mechanical control device' },
    { id: 'pipe', name: 'Pipe', icon: 'Pipe', description: 'Create a pipe' },
    { id: 'pipeplaceholder', name: 'Pipe Placeholder', icon: 'PipePlaceholder', description: 'Create a pipe placeholder' },
    { id: 'parallelpipes', name: 'Parallel Pipes', icon: 'ParallelPipes', description: 'Create parallel pipes' },
    { id: 'pipefitting', name: 'Pipe Fitting', icon: 'PipeFitting', description: 'Create a pipe fitting' },
    { id: 'pipeaccessory', name: 'Pipe Accessory', icon: 'PipeAccessory', description: 'Create a pipe accessory' },
    { id: 'flexpipe', name: 'Flex Pipe', icon: 'FlexPipe', description: 'Create a flex pipe' },
    { id: 'plumbingequipment', name: 'Plumbing Equipment', icon: 'PlumbingEquipment', description: 'Place plumbing equipment' },
    { id: 'plumbingfixture', name: 'Plumbing Fixture', icon: 'PlumbingFixture', description: 'Place plumbing fixture' },
    { id: 'sprinkler', name: 'Sprinkler', icon: 'Sprinkler', description: 'Place a sprinkler' },
    { id: 'wire', name: 'Wire', icon: 'Wire', description: 'Create a wire' },
    { id: 'cabletray', name: 'Cable Tray', icon: 'CableTray', description: 'Create a cable tray' },
    { id: 'conduit', name: 'Conduit', icon: 'Conduit', description: 'Create a conduit' },
    { id: 'parallelconduits', name: 'Parallel Conduits', icon: 'ParallelConduits', description: 'Create parallel conduits' },
    { id: 'cabletrayfitting', name: 'Cable Tray Fitting', icon: 'CableTrayFitting', description: 'Create a cable tray fitting' },
    { id: 'conduitfitting', name: 'Conduit Fitting', icon: 'ConduitFitting', description: 'Create a conduit fitting' },
    { id: 'electricalequipment', name: 'Electrical Equipment', icon: 'ElectricalEquipment', description: 'Place electrical equipment' },
    { id: 'device', name: 'Device', icon: 'Device', description: 'Place a device' },
    { id: 'lightingfixture', name: 'Lighting Fixture', icon: 'LightingFixture', description: 'Place a lighting fixture' },
    { id: 'set', name: 'Set', icon: 'Set', description: 'Set work plane' },
    { id: 'show', name: 'Show', icon: 'Show', description: 'Show work plane' },
    { id: 'refplane', name: 'Ref Plane', icon: 'RefPlane', description: 'Create a reference plane' },
    { id: 'viewer', name: 'Viewer', icon: 'Viewer', description: 'Open viewer' }
  ]
};
